name: flutter_flame_architecture
description: A new Flutter package project.
version: 0.0.1
author: William Verhaeghe
homepage: google.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flame: ^1.0.0-releasecandidate.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
